apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rallyroo-deployment-alert-webhook
  namespace: rallyroo
  labels:
    app.kubernetes.io/name: rallyroo
    app.kubernetes.io/component: deployment-alerting
spec:
  itemPath: vaults/rallyroo-prod/items/rallyroo-deployment-alert-webhook
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rallyroo-postgres
  namespace: rallyroo
  labels:
    app.kubernetes.io/name: rallyroo
    app.kubernetes.io/component: postgres
spec:
  itemPath: vaults/rallyroo-prod/items/rallyroo-postgres
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: rallyroo-stytch
  namespace: rallyroo
  labels:
    app.kubernetes.io/name: rallyroo
    app.kubernetes.io/component: identity
spec:
  itemPath: vaults/rallyroo-prod/items/rallyroo-stytch
