api:
  image:
    repository: rallyroo-api
    tag: local
    pullPolicy: IfNotPresent

postgres:
  persistence:
    mode: hostPath
    hostPath: /var/local/rallyroo/postgres

redis:
  persistence:
    mode: hostPath
    hostPath: /var/local/rallyroo/redis

nginx:
  service:
    type: NodePort
    nodePort: 30080
