#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)
WORKER_DIR="$ROOT/deploy/alerts/resend-worker"
KUBECONFIG_PATH=${RALLYROO_KUBECONFIG:-$HOME/.rallyroo/kubeconfig}
CONTEXT=${RALLYROO_CONTEXT:-kind-rallyroo}

banner "Rallyroo deployment email alerts"

stage "Prerequisites and Cloudflare login"
for command in node npm npx openssl curl kubectl flux; do
  command -v "$command" >/dev/null || { warn "$command is required"; exit 1; }
done
[[ -f "$KUBECONFIG_PATH" ]] || { warn "Missing $KUBECONFIG_PATH"; exit 1; }
step "Install the pinned Worker dependencies."
(cd "$WORKER_DIR" && npm ci)
if ! (cd "$WORKER_DIR" && npx wrangler whoami >/dev/null 2>&1); then
  step "Approve the Cloudflare OAuth request opened by Wrangler. Credentials will use your OS keychain."
  (cd "$WORKER_DIR" && npx wrangler login --use-keyring)
fi
(cd "$WORKER_DIR" && npx wrangler whoami >/dev/null)
say "Cloudflare authentication is ready."
pause "Continue to Resend?"

stage "Resend sending key and recipient"
open_url "https://resend.com/api-keys"
step "Click Create API Key and name it 'Rallyroo deployment alerts'."
step "Choose Sending access and restrict it to the verified Rallyroo sending domain when available."
step "Create the key and copy it now; Resend shows it only once."
ask_secret RESEND_API_KEY "Paste the Resend API key:"
[[ "$RESEND_API_KEY" == re_* ]] || { warn "The Resend key should start with re_"; exit 1; }
ask ALERT_RECIPIENT "Email address that should receive deployment alerts:"
[[ "$ALERT_RECIPIENT" == *@*.* ]] || { warn "Enter a valid recipient email address"; exit 1; }
pause "Continue after the key and recipient are correct?"

stage "Resend template and Automation"
open_url "https://resend.com/templates"
step "Create a template named 'Rallyroo deployment failed'."
step "Import or paste deploy/alerts/resend-worker/resend-template.html."
step "Set the sender to a verified Rallyroo address and subject to '[Rallyroo] Deployment failed: {{{REASON}}}'."
step "Define these string variables: APPLICATION, ENVIRONMENT, OBJECT, NAMESPACE, REASON, MESSAGE, REVISION, TIMESTAMP."
step "Publish the template. Draft templates cannot be used by Automations."
open_url "https://resend.com/automations"
step "Create an Automation named 'Rallyroo deployment failures' with custom event trigger deployment.failed."
step "Add Send Email, select the published template, and map each template variable to the matching lowercase event field."
step "The mappings are APPLICATION→event.application through TIMESTAMP→event.timestamp."
step "Start the Automation. Enabled Automations cannot be edited without duplicating them."
pause "Continue after the Automation shows Enabled?"

stage "Deploy the signed Flux adapter"
FLUX_HMAC_SECRET=$(openssl rand -hex 32)
secrets_file=$(mktemp)
deploy_log=$(mktemp)
trap 'rm -f "${secrets_file:-}" "${deploy_log:-}"' EXIT
chmod 600 "$secrets_file"
printf 'FLUX_HMAC_SECRET=%s\nRESEND_API_KEY=%s\nALERT_RECIPIENT=%s\n' \
  "$FLUX_HMAC_SECRET" "$RESEND_API_KEY" "$ALERT_RECIPIENT" >"$secrets_file"
step "Deploy the Worker and upload all three values as encrypted Worker secrets."
(cd "$WORKER_DIR" && npx wrangler deploy --secrets-file "$secrets_file") | tee "$deploy_log"
rm -f "$secrets_file"
WORKER_BASE_URL=$(grep -Eo 'https://[^[:space:]]+\.workers\.dev' "$deploy_log" | tail -n1 || true)
if [[ -z "$WORKER_BASE_URL" ]]; then
  ask WORKER_BASE_URL "Paste the HTTPS Worker URL printed by Wrangler:"
fi
WORKER_BASE_URL=${WORKER_BASE_URL%/}
[[ "$WORKER_BASE_URL" == https://* ]] || { warn "Worker URL must use HTTPS"; exit 1; }
curl --fail --silent --output /dev/null "$WORKER_BASE_URL/health"
say "Worker health check passed."
pause "Continue to connect Flux?"

stage "Connect Flux using the shared HMAC key"
export RALLYROO_KUBECONFIG="$KUBECONFIG_PATH"
export RALLYROO_DEPLOYMENT_ALERT_WEBHOOK_URL="$WORKER_BASE_URL/flux"
export RALLYROO_DEPLOYMENT_ALERT_HMAC_SECRET="$FLUX_HMAC_SECRET"
"$ROOT/deploy/local/enable-flux.sh"
unset RALLYROO_DEPLOYMENT_ALERT_WEBHOOK_URL RALLYROO_DEPLOYMENT_ALERT_HMAC_SECRET
kubectl --kubeconfig "$KUBECONFIG_PATH" --context "$CONTEXT" -n rallyroo get provider,alert
say "Flux now signs HelmRelease error events; the Worker verifies them before contacting Resend."
pause "Continue to the delivery test?"

stage "Verify end-to-end email delivery"
export RALLYROO_DEPLOYMENT_ALERT_WEBHOOK_URL="$WORKER_BASE_URL/flux"
export RALLYROO_DEPLOYMENT_ALERT_HMAC_SECRET="$FLUX_HMAC_SECRET"
(cd "$WORKER_DIR" && npm run test:delivery)
unset RALLYROO_DEPLOYMENT_ALERT_WEBHOOK_URL RALLYROO_DEPLOYMENT_ALERT_HMAC_SECRET
open_url "https://resend.com/automations"
step "Open Rallyroo deployment failures → Runs and confirm the setup-test run completed."
step "Confirm the deployment alert arrived at the recipient inbox."
confirm "Did the Automation run complete and the email arrive?" || {
  warn "Alert delivery is not verified. Inspect the Automation run and Worker logs before relying on it."
  exit 1
}

finish
